package production;

import java.util.Random;

public class CustomerList {
    private static final Customer[] customers = {
            new Customer("Fred Frazier", "52510 Waubesa Drive"),
            new Customer("Jane Tucker", "1 Fisk Road"),
            new Customer("Steven Armstrong", "360 Sloan Crossing"),
            new Customer("Doris Cox", "1455 Blue Bill Park Avenue"),
            new Customer("Annie Hayes", "12 Bultman Trail"),
            new Customer("Gloria Harvey", "70 Eagle Crest Pass"),
            new Customer("Katherine Perez", "54 Coolidge Road"),
            new Customer("Kevin Williams", "0084 Meadow Vale Drive"),
            new Customer("Samuel Howard", "03020 Badeau Terrace"),
            new Customer("Clarence Bell", "8430 Bobwhite Parkway"),
            new Customer("Lisa Anderson", "4 Pankratz Court"),
            new Customer("Henry Perkins", "13123 Bunker Hill Court"),
            new Customer("Pamela Howell", "2599 Trailsway Trail"),
            new Customer("Sarah Cook", "04021 Chive Pass"),
            new Customer("Donna West", "243 Eagle Crest Pass"),
            new Customer("Louise Price", "4 Delaware Crossing"),
            new Customer("Donna Ford", "805 Carpenter Crossing"),
            new Customer("Carol Morales", "0856 Oxford Parkway"),
            new Customer("Arthur Sanders", "1403 Dahle Trail"),
            new Customer("Richard Morris", "0 Pennsylvania Way"),
            new Customer("Lois Powell", "13 Dayton Park"),
            new Customer("Jason Hawkins", "4 Logan Drive"),
            new Customer("Paula King", "51 Fairfield Place"),
            new Customer("Tammy Stephens", "0717 Clyde Gallagher Court"),
            new Customer("Susan Mitchell", "73975 Bartelt Street"),
            new Customer("Steven Gardner", "5903 Chinook Plaza"),
            new Customer("Johnny Carter", "4002 Ohio Avenue"),
            new Customer("Jennifer Richardson", "3587 Monterey Junction"),
            new Customer("Julie West", "408 Maple Alley"),
            new Customer("Linda Perez", "91 Dorton Street"),
            new Customer("Janet Russell", "56 Gerald Lane"),
            new Customer("Philip Lynch", "6 Arizona Way"),
            new Customer("Bobby Mccoy", "419 Fieldstone Road"),
            new Customer("Roger Ramos", "33 1st Avenue"),
            new Customer("Daniel Hart", "37 Independence Place"),
            new Customer("Linda Hunter", "023 Nancy Junction"),
            new Customer("Richard Nguyen", "5 Thackeray Terrace"),
            new Customer("Harry Hawkins", "76863 Towne Crossing"),
            new Customer("Jonathan Lopez", "764 Bunting Drive"),
            new Customer("Elizabeth Peters", "96 Dixon Street"),
            new Customer("Jennifer Henderson", "249 Beilfuss Alley"),
            new Customer("Steve Olson", "8655 Fieldstone Avenue"),
            new Customer("Kathleen Brooks", "1 Lakewood Gardens Trail"),
            new Customer("Nicholas Hughes", "3 Mosinee Place"),
            new Customer("Maria Wright", "1 Prentice Pass"),
            new Customer("Laura Stevens", "0 Killdeer Place"),
            new Customer("Benjamin Fowler", "06552 Division Court"),
            new Customer("Bruce Lewis", "62 Rigney Hill"),
            new Customer("Tammy Perry", "1 Lien Alley"),
            new Customer("Annie Fields", "31 Pawling Court"),
            new Customer("Paul Fuller", "249 Anderson Alley"),
            new Customer("Irene Woods", "84 New Castle Way"),
            new Customer("Phillip Berry", "2050 Schiller Lane"),
            new Customer("Norma Diaz", "6 Rockefeller Center"),
            new Customer("Alan Hanson", "826 Bobwhite Lane"),
            new Customer("Robin Sanchez", "7622 American Point"),
            new Customer("Ann Murphy", "9977 Forest Court"),
            new Customer("Susan Dunn", "3 Hoard Trail"),
            new Customer("Carolyn Spencer", "44075 High Crossing Pass"),
            new Customer("Howard Payne", "52 Merry Junction"),
            new Customer("Tina Hernandez", "77 Nelson Lane"),
            new Customer("Marie Gardner", "38 Judy Circle"),
            new Customer("Cynthia Young", "12 Waxwing Plaza"),
            new Customer("Beverly Robertson", "2 Eastwood Trail"),
            new Customer("Frances Hawkins", "153 Bayside Court"),
            new Customer("Samuel Parker", "48 Golf Circle"),
            new Customer("Kathy Gibson", "8398 Chinook Hill"),
            new Customer("Thomas Sanchez", "00025 Carioca Crossing"),
            new Customer("Wanda Perez", "928 Duke Court"),
            new Customer("Carolyn Rose", "743 Algoma Terrace"),
            new Customer("Gary Jordan", "246 Bashford Court"),
            new Customer("Amy Arnold", "5 Reinke Court"),
            new Customer("Mildred Phillips", "760 Meadow Vale Avenue"),
            new Customer("Lillian Ferguson", "827 High Crossing Way"),
            new Customer("Ralph White", "35330 Eliot Avenue"),
            new Customer("Amanda Walker", "05174 Rusk Lane"),
            new Customer("Paula Cruz", "19313 Bayside Pass"),
            new Customer("Andrea Morrison", "16342 Clarendon Hill"),
            new Customer("Scott Black", "6 Milwaukee Lane"),
            new Customer("Jonathan Rivera", "38509 Corben Point"),
            new Customer("Jose Ellis", "94479 Scofield Hill"),
            new Customer("Harold Ramos", "1 Pond Hill"),
            new Customer("Janice Woods", "0 Nobel Road"),
            new Customer("Gregory Cook", "27 Everett Terrace"),
            new Customer("Mildred Nguyen", "02274 Briar Crest Junction"),
            new Customer("Juan Ray", "291 Morningstar Plaza"),
            new Customer("Amy Nelson", "9 Twin Pines Crossing"),
            new Customer("Martin Ryan", "8 Bobwhite Plaza"),
            new Customer("Angela Andrews", "76 Warrior Junction"),
            new Customer("Anne Myers", "1883 Hollow Ridge Street"),
            new Customer("David Price", "9150 Linden Hill"),
            new Customer("Stephen Mitchell", "3642 Sutherland Park"),
            new Customer("Ann Russell", "18 Charing Cross Crossing"),
            new Customer("Denise Miller", "9 Gina Avenue"),
            new Customer("Benjamin Cruz", "61 Hovde Alley"),
            new Customer("Christopher Gardner", "5 Mccormick Parkway"),
            new Customer("Howard Fernandez", "84031 Summit Parkway"),
            new Customer("Lawrence Lee", "8 Annamark Center"),
            new Customer("Roger Adams", "326 Fair Oaks Alley"),
            new Customer("Shawn Lawson", "05 Mitchell Circle")
    };

    static Customer RandomCustomer() {
        Random r = new Random();
        return customers[r.nextInt(99)];
    }

}